name: Lubiland
favicon: null
layout_spectrum: 1
typography_spectrum: 0.55673
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#172033'
    - '#ffffff'
    - '#00ffff'
    - '#759bec'
    - '#0000ff'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.75
purpose: []
