name: Lubiland
favicon: null
layout_spectrum: 0.1419326327741146
typography_spectrum: 0.976217019604519
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#172033'
    - '#ffffff'
    - '#00ffff'
    - '#759bec'
    - '#0000ff'
  brandStrength: 0.3125
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
